### ISSUE TITLE
TODO-list

### ISSUE THREAD

**Issue by fuzzyjellyrock** [fuzzyjellyrock/java-invaders#2]
- [x] Eliminar las barreras.
- [x] Los controles no responden después de iniciar un nuevo juego o abrir una nueva ventana.
- [ ] Cambiar la documentación.
- [x] Cambiar el diseño del juego.
- [ ] Avanzar de nivel funciona correctamente. Los aliens se quedan atascados por el momento.
